services:
  database:
    image: mysql:8.0
    container_name: bsu_db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.db_env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bsu_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: bsu_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app   
      - static_volume:/app/static 
    #ports:
    #  - "8000:8000"
    depends_on:
      database:    
        condition: service_healthy
    networks:
      - bsu_network
    restart: always

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: bsu_frontend
    #ports:
     # - "5173:5173"
    depends_on:
      - backend
    networks:
      - bsu_network
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    restart: always

  nginx:
    build: ./nginx
    container_name: bsu_gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - static_volume:/app/static # To serve Admin CSS
    networks:
      - bsu_network


volumes:
  db_data:
  static_volume:

networks:
  bsu_network:
    name: bsu_network